extends SceneTree

## Headless tests for the map importer.
##
##   godot --headless --path . --script tests/run_map_tests.gd
##
## There is no CS2 install here, so these do not test dust2. What they test is
## the thing that would otherwise only be discovered the first time someone
## runs the extraction: that a glTF full of meshes and materials comes back as
## geometry you can stand on, that collision-marked materials are picked out
## correctly, and that the fallback for a map with no collision geometry works.
##
## The fixture is generated by Godot's own glTF exporter into user://, so the
## test is self-contained and nothing Valve-derived is involved.

const FIXTURE_PATH := "user://test_map.gltf"

## Matches one of MapImporter's default collision_material_hints.
const CLIP_MATERIAL := "tools_playerclip"
const VISUAL_MATERIAL := "world_wall"

const FLOOR_SIZE := Vector3(512.0, 32.0, 512.0)

var _failures: int = 0
var _checks: int = 0
var _frames: int = 0

var _importer: MapImporter
var _player: CharacterBody3D
var _auto_stats: Dictionary
var _all_stats: Dictionary


func _process(_delta: float) -> bool:
	_frames += 1

	if _frames == 1:
		if not _write_fixture():
			_report()
			return true
		return false

	if _frames == 2:
		_test_auto_import()
		return false

	if _frames == 3:
		_test_all_meshes_import()
		_spawn_player()
		return false

	# Give the player time to fall onto the imported floor.
	if _frames < 140:
		return false

	_test_player_stands_on_imported_map()
	if _importer != null:
		_importer.free()
	_report()
	return true


# --- Fixture --------------------------------------------------------------

## Builds a two-mesh scene and writes it out as glTF: a floor whose material
## name marks it as collision, and a wall that is only decoration. Round
## tripping through Godot's own exporter is what makes this a real test of the
## importer rather than of a handwritten glTF.
func _write_fixture() -> bool:
	var fixture := Node3D.new()
	fixture.name = "TestMap"
	# The wall sits inside the floor's footprint so the reported bounds are
	# exactly the floor's, which makes the scale assertion below unambiguous.
	_add_mesh(fixture, "Floor", FLOOR_SIZE, Vector3.ZERO, CLIP_MATERIAL)
	_add_mesh(
		fixture, "Wall", Vector3(64.0, 128.0, 64.0),
		Vector3(128.0, 64.0, 0.0), VISUAL_MATERIAL
	)

	var document := GLTFDocument.new()
	var state := GLTFState.new()
	var error := document.append_from_scene(fixture, state)
	_check(error == OK, "fixture scene converts to glTF (error %d)" % error)
	if error != OK:
		return false

	error = document.write_to_filesystem(state, FIXTURE_PATH)
	_check(error == OK, "fixture glTF is written (error %d)" % error)
	fixture.free()
	return error == OK


## Owner has to be set after the node is in the tree, and glTF export needs
## owners set across the whole subtree.
func _add_mesh(
	parent: Node3D,
	node_name: String,
	size: Vector3,
	at: Vector3,
	material_name: String
) -> void:
	var mesh := BoxMesh.new()
	mesh.size = size

	var material := StandardMaterial3D.new()
	material.resource_name = material_name
	mesh.surface_set_material(0, material)

	var instance := MeshInstance3D.new()
	instance.name = node_name
	instance.mesh = mesh
	instance.position = at

	parent.add_child(instance)
	instance.owner = parent


func _make_importer(mode: MapImporter.CollisionSource) -> MapImporter:
	var importer := MapImporter.new()
	importer.source_path = FIXTURE_PATH
	importer.collision_source = mode
	importer.report = false
	return importer


# --- Tests ----------------------------------------------------------------

## The default: a map that ships collision geometry should use that and
## nothing else, because visual geometry is not a collision hull.
func _test_auto_import() -> void:
	var importer := _make_importer(MapImporter.CollisionSource.AUTO)
	root.add_child(importer)
	_auto_stats = importer.stats
	_importer = importer

	_check(
		not _auto_stats.has("error"),
		"importer loaded the glTF (%s)" % _auto_stats.get("error", "")
	)
	_check_equal(_auto_stats.get("meshes", 0), 2, "both meshes were found")
	_check_equal(
		_auto_stats.get("collision_marked", 0), 1,
		"the clip-material mesh was recognised as collision"
	)
	_check_equal(
		_auto_stats.get("visible", 0), 1,
		"the other mesh stayed visible"
	)
	_check_equal(
		_auto_stats.get("collision_bodies", 0), 1,
		"auto mode builds collision only from the collision-marked mesh"
	)
	_check(
		int(_auto_stats.get("collision_triangles", 0)) >= 12,
		"the floor collider is a real trimesh (%d triangles)"
			% _auto_stats.get("collision_triangles", 0)
	)

	var bounds: AABB = _auto_stats.get("bounds", AABB())
	_check(
		absf(bounds.size.x - FLOOR_SIZE.x) < 1.0,
		"reported bounds match the fixture (%.1f wide, expected %.1f)"
			% [bounds.size.x, FLOOR_SIZE.x]
	)


## The fallback for an export with no collision geometry at all: collide
## against everything, because something is better than falling through.
func _test_all_meshes_import() -> void:
	var importer := _make_importer(MapImporter.CollisionSource.ALL_MESHES)
	root.add_child(importer)
	_all_stats = importer.stats
	_check_equal(
		_all_stats.get("collision_bodies", 0), 2,
		"all-meshes mode builds collision from every mesh"
	)
	importer.queue_free()


func _spawn_player() -> void:
	var scene: PackedScene = load("res://src/player/player.tscn")
	_player = scene.instantiate() as CharacterBody3D
	_importer.add_child(_player)
	# Above the imported floor, whose top sits at half its height.
	_player.global_position = Vector3(0.0, FLOOR_SIZE.y * 0.5 + 24.0, 0.0)


## The point of the whole exercise: can you stand on an imported map.
func _test_player_stands_on_imported_map() -> void:
	_check(_player != null, "player was spawned on the imported map")
	if _player == null:
		return
	var body := _player as PlayerBody
	_check(body.on_ground, "player is standing on the imported geometry")
	var expected := FLOOR_SIZE.y * 0.5
	_check(
		absf(body.global_position.y - expected) < 2.0,
		"player settled on the floor surface (y = %.2f, expected %.2f)"
			% [body.global_position.y, expected]
	)


# --- Harness --------------------------------------------------------------

func _check(condition: bool, description: String) -> void:
	_checks += 1
	if condition:
		return
	_failures += 1
	printerr("FAIL: %s" % description)


func _check_equal(actual: Variant, expected: Variant, description: String) -> void:
	_checks += 1
	if actual == expected:
		return
	_failures += 1
	printerr("FAIL: %s (expected %s, got %s)" % [description, expected, actual])


func _report() -> void:
	if _failures == 0:
		print("%d map checks passed." % _checks)
		quit(0)
	else:
		printerr("%d of %d map checks failed." % [_failures, _checks])
		quit(1)
