extends SceneTree

## Headless tests for the map importer.
##
##   godot --headless --path . --script tests/run_map_tests.gd
##
## There is no CS2 install here, so these do not test dust2. What they test is
## the thing that would otherwise only be discovered the first time someone
## runs the extraction: that a glTF full of meshes and materials comes back as
## geometry you can stand on, that collision-marked materials are picked out
## correctly, and that the fallback for a map with no collision geometry works.
##
## The fixture is generated by Godot's own glTF exporter into user://, so the
## test is self-contained and nothing Valve-derived is involved.

const FIXTURE_PATH := "user://test_map.gltf"

## Matches one of MapImporter's default collision_material_hints.
const CLIP_MATERIAL := "tools_playerclip"
const VISUAL_MATERIAL := "world_wall"

const FLOOR_SIZE := Vector3(512.0, 32.0, 512.0)

## A second fixture shaped like what Source 2 Viewer really writes: the world
## in metres with a sun in it, and the collision hull as a separate file, in
## inches under a node that scales it down to metres.
const EXPORT_WORLD_PATH := "user://export_fixture/map/world.gltf"
const EXPORT_DECOY_PATH := "user://export_fixture/map/aaa_physics.gltf"
const EXPORT_HULL_PATH := "user://export_fixture/hull/world_physics_physics.gltf"
const METRES := 0.0254

## The hull's floor is lower than the visible one, so where the player comes to
## rest says which of the two was solid.
const HULL_FLOOR_SIZE := Vector3(512.0, 16.0, 512.0)

## Well away from the first fixture, which is also at the origin.
const EXPORT_OFFSET := Vector3(4096.0, 0.0, 0.0)

const SETTLE_TICKS := 320

var _failures: int = 0
var _checks: int = 0
var _frames: int = 0
var _spawned_at_tick: int = 0

var _importer: MapImporter
var _export_importer: MapImporter
var _player: CharacterBody3D
var _export_player: CharacterBody3D
var _auto_stats: Dictionary
var _all_stats: Dictionary


func _process(_delta: float) -> bool:
	_frames += 1

	if _frames == 1:
		if not (_write_fixture() and _write_export_fixture()):
			_report()
			return true
		return false

	if _frames == 2:
		_test_auto_import()
		return false

	if _frames == 3:
		_test_all_meshes_import()
		_test_export_shaped_import()
		_test_file_picking()
		_test_entities()
		_test_export_offset_fix()
		_test_paint_channel()
		_test_blend_materials()
		_test_lighting()
		_spawn_player()
		_spawned_at_tick = Engine.get_physics_frames()
		return false

	# Give the players time to fall onto the imported floors.
	if Engine.get_physics_frames() - _spawned_at_tick < SETTLE_TICKS:
		return false

	_test_player_stands_on_imported_map()
	_test_player_stands_on_the_hull()
	if _importer != null:
		_importer.free()
	if _export_importer != null:
		_export_importer.free()
	_report()
	return true


# --- Fixture --------------------------------------------------------------

## Builds a two-mesh scene and writes it out as glTF: a floor whose material
## name marks it as collision, and a wall that is only decoration. Round
## tripping through Godot's own exporter is what makes this a real test of the
## importer rather than of a handwritten glTF.
func _write_fixture() -> bool:
	var fixture := Node3D.new()
	fixture.name = "TestMap"
	# The wall sits inside the floor's footprint so the reported bounds are
	# exactly the floor's, which makes the scale assertion below unambiguous.
	_add_mesh(fixture, "Floor", FLOOR_SIZE, Vector3.ZERO, CLIP_MATERIAL)
	_add_mesh(
		fixture, "Wall", Vector3(64.0, 128.0, 64.0),
		Vector3(128.0, 64.0, 0.0), VISUAL_MATERIAL
	)

	return _write_gltf(fixture, FIXTURE_PATH)


func _write_gltf(scene: Node3D, path: String) -> bool:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))

	var document := GLTFDocument.new()
	var state := GLTFState.new()
	var error := document.append_from_scene(scene, state)
	_check(error == OK, "%s converts to glTF (error %d)" % [path.get_file(), error])
	if error == OK:
		error = document.write_to_filesystem(state, path)
		_check(error == OK, "%s is written (error %d)" % [path.get_file(), error])
	scene.free()
	return error == OK


func _write_export_fixture() -> bool:
	# The world: the same floor as the first fixture, in metres, plus a sun at
	# the kind of intensity the real export carries.
	var world := Node3D.new()
	world.name = "World"
	_add_mesh(world, "Floor", FLOOR_SIZE * METRES, Vector3.ZERO, VISUAL_MATERIAL)
	var sun := DirectionalLight3D.new()
	sun.name = "light_environment"
	sun.light_energy = 1707.5
	sun.rotation_degrees = Vector3(-50.0, 30.0, 0.0)
	world.add_child(sun)
	sun.owner = world

	# The hull: inches, under a node that scales to metres. A floor, and a
	# grenade clip hanging over it that a player has to fall straight through.
	var hull := Node3D.new()
	hull.name = "Hull"
	var to_metres := Node3D.new()
	to_metres.name = "ToMetres"
	to_metres.scale = Vector3.ONE * METRES
	hull.add_child(to_metres)
	to_metres.owner = hull
	_add_mesh(to_metres, "physics_group_concrete", HULL_FLOOR_SIZE, Vector3.ZERO, "", hull)
	_add_mesh(
		to_metres, "physics_csgo_grenadeclip", Vector3(256.0, 16.0, 256.0),
		Vector3(0.0, 72.0, 0.0), "", hull
	)

	# Something that sorts ahead of world.gltf and must not be mistaken for it.
	var decoy := Node3D.new()
	decoy.name = "Decoy"
	_add_mesh(decoy, "Decoy", Vector3.ONE, Vector3.ZERO, VISUAL_MATERIAL)

	return (
		_write_gltf(world, EXPORT_WORLD_PATH)
		and _write_gltf(hull, EXPORT_HULL_PATH)
		and _write_gltf(decoy, EXPORT_DECOY_PATH)
	)


## Owner has to be set after the node is in the tree, and glTF export needs
## owners set across the whole subtree.
func _add_mesh(
	parent: Node3D,
	node_name: String,
	size: Vector3,
	at: Vector3,
	material_name: String,
	scene_root: Node3D = null
) -> void:
	var mesh := BoxMesh.new()
	mesh.size = size

	if not material_name.is_empty():
		var material := StandardMaterial3D.new()
		material.resource_name = material_name
		mesh.surface_set_material(0, material)

	var instance := MeshInstance3D.new()
	instance.name = node_name
	instance.mesh = mesh
	instance.position = at

	parent.add_child(instance)
	instance.owner = scene_root if scene_root != null else parent


func _make_importer(mode: MapImporter.CollisionSource) -> MapImporter:
	var importer := MapImporter.new()
	importer.source_path = FIXTURE_PATH
	importer.collision_source = mode
	importer.report = false
	return importer


# --- Tests ----------------------------------------------------------------

## The default: a map that ships collision geometry should use that and
## nothing else, because visual geometry is not a collision hull.
func _test_auto_import() -> void:
	var importer := _make_importer(MapImporter.CollisionSource.AUTO)
	root.add_child(importer)
	_auto_stats = importer.stats
	_importer = importer

	_check(
		not _auto_stats.has("error"),
		"importer loaded the glTF (%s)" % _auto_stats.get("error", "")
	)
	_check_equal(_auto_stats.get("meshes", 0), 2, "both meshes were found")
	_check_equal(
		_auto_stats.get("collision_marked", 0), 1,
		"the clip-material mesh was recognised as collision"
	)
	_check_equal(
		_auto_stats.get("visible", 0), 1,
		"the other mesh stayed visible"
	)
	_check_equal(
		_auto_stats.get("collision_bodies", 0), 1,
		"auto mode builds collision only from the collision-marked mesh"
	)
	_check(
		int(_auto_stats.get("collision_triangles", 0)) >= 12,
		"the floor collider is a real trimesh (%d triangles)"
			% _auto_stats.get("collision_triangles", 0)
	)

	var bounds: AABB = _auto_stats.get("bounds", AABB())
	_check(
		absf(bounds.size.x - FLOOR_SIZE.x) < 1.0,
		"reported bounds match the fixture (%.1f wide, expected %.1f)"
			% [bounds.size.x, FLOOR_SIZE.x]
	)


## The fallback for an export with no collision geometry at all: collide
## against everything, because something is better than falling through.
func _test_all_meshes_import() -> void:
	var importer := _make_importer(MapImporter.CollisionSource.ALL_MESHES)
	root.add_child(importer)
	_all_stats = importer.stats
	_check_equal(
		_all_stats.get("collision_bodies", 0), 2,
		"all-meshes mode builds collision from every mesh"
	)
	importer.queue_free()


## An import shaped like the real thing: metres, a sun, a separate hull. This
## is the path dust2 takes, and the one where a scale applied twice, or not at
## all, shows up.
func _test_export_shaped_import() -> void:
	var map_file := MapImporter.find_map_file(EXPORT_WORLD_PATH.get_base_dir())
	_check_equal(map_file, EXPORT_WORLD_PATH, "world.gltf is picked over a glTF that sorts before it")

	var importer := MapImporter.new()
	importer.source_path = map_file
	importer.collision_path = MapImporter.find_collision_file(EXPORT_HULL_PATH.get_base_dir())
	importer.scale_factor = MapImporter.SOURCE2_VIEWER_SCALE
	# Reporting on, into a file of its own: the report is what gets sent over
	# when an import misbehaves, so it has to say the things that were found.
	importer.report = true
	importer.report_path = "user://export_fixture/map-report.txt"
	importer.position = EXPORT_OFFSET
	root.add_child(importer)
	_export_importer = importer
	var stats := importer.stats

	_check(not stats.has("error"), "export-shaped fixture loaded (%s)" % stats.get("error", ""))
	var bounds: AABB = stats.get("bounds", AABB())
	_check(
		absf(bounds.size.x - FLOOR_SIZE.x) < 1.0 and absf(bounds.size.y - FLOOR_SIZE.y) < 1.0,
		"a map in metres comes out in inches, once (%.1f x %.1f, expected %.1f x %.1f)"
			% [bounds.size.x, bounds.size.y, FLOOR_SIZE.x, FLOOR_SIZE.y]
	)
	_check(
		bounds.get_center().distance_to(EXPORT_OFFSET) < 1.0,
		"bounds are in world space (centre %s, expected %s)" % [bounds.get_center(), EXPORT_OFFSET]
	)

	_check_equal(stats.get("collision_from", ""), "the collision hull", "collision comes from the hull")
	_check_equal(
		stats.get("collision_bodies", 0), 1,
		"the hull's grenade clip is left out and the world adds nothing"
	)
	_check(stats.has("sun"), "the export's sun is reported")

	var written := FileAccess.get_file_as_string(importer.report_path)
	for expected: String in ["from the collision hull", "512 x 32 x 512 units", "sun:", VISUAL_MATERIAL]:
		_check(written.contains(expected), "the report file says \"%s\"" % expected)
	_check_equal(
		importer.find_children("*", "Light3D", true, false).size(), 0,
		"the export's lights are taken out of the scene"
	)
	var hull := importer.get_node_or_null("CollisionHull") as Node3D
	_check(hull != null and not hull.visible, "the hull is not drawn")

	for shape in importer.find_children("*", "CollisionShape3D", true, false):
		_check(
			(shape as Node3D).global_transform.basis.get_scale().is_equal_approx(Vector3.ONE),
			"collision shapes are not scaled (%s)" % shape.name
		)


func _test_file_picking() -> void:
	_check_equal(
		MapImporter.find_collision_file(EXPORT_HULL_PATH.get_base_dir()), EXPORT_HULL_PATH,
		"the hull glTF is found"
	)
	_check_equal(
		MapImporter.find_map_file(EXPORT_HULL_PATH.get_base_dir()), "",
		"a directory of nothing but physics files has no world in it"
	)
	_check_equal(
		MapImporter.find_map_file("user://export_fixture"), EXPORT_WORLD_PATH,
		"the search goes into subdirectories"
	)
	_check_equal(
		MapImporter.find_map_file("user://export_fixture/not_there"), "",
		"a directory that does not exist has no map in it, and that is not an error"
	)


## Synthetic, but every awkward thing the real file does is in here: CRLF,
## padded keys, both multi-line value forms, an I/O line, keys before and
## after classname.
func _test_entities() -> void:
	var path := "user://export_fixture/entities.vents"
	var lines := PackedStringArray([
		"====0====",
		'classname                      "worldspawn"',
		"@OnMapSpawn SetBloomScale tonemap 0",
		"",
		"====1====",
		"enabled                        true",
		"priority                       1",
		'classname                      "info_player_counterterrorist"',
		"origin                         [ 10.0, 20.0, 30.0 ]",
		"angles                         [ 0.0, 90.0, 0.0 ]",
		"",
		"====2====",
		'classname                      "path_particle_rope_clientside"',
		'pathnodes                      """',
		"[",
		"\t1.0 2.0 3.0",
		"]",
		'"""',
		"precomputed_vis_clusters       [",
		"\t4, 5, 6",
		"]",
		"origin                         [ 1.0, 2.0, 3.0 ]",
		"",
		"====3====",
		"priority                       0",
		'classname                      "info_player_counterterrorist"',
		"origin                         [ -40.0, 50.0, -60.0 ]",
		"angles                         [ 0.0, -135.0, 0.0 ]",
		"",
		"====4====",
		"enabled                        false",
		'classname                      "info_player_terrorist"',
		"origin                         [ 0.0, 0.0, 0.0 ]",
		"",
		"====5====",
		'classname                      "info_player_terrorist"',
		"origin                         [ 7.0, 8.0, 9.0 ]",
		"angles                         [ 0.0, 0.0, 0.0 ]",
	])
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string("\r\n".join(lines) + "\r\n")
	file.close()

	var entities := SourceEntities.parse(path)
	_check_equal(entities.size(), 6, "every entity block is read")
	_check_equal(
		entities[2].keys().size() if entities.size() > 2 else -1, 2,
		"multi-line values are skipped without leaking keys"
	)

	var spawns := SourceEntities.player_spawns(entities)
	_check_equal(spawns["T"].size(), 1, "a disabled spawn is not offered")
	_check_equal(spawns["CT"].size(), 2, "both CT spawns are found")
	if spawns["CT"].size() == 2:
		_check_equal(spawns["CT"][0]["priority"], 0, "the spawns the game fills first come first")
		_check(
			(spawns["CT"][0]["position"] as Vector3).is_equal_approx(Vector3(50.0, -60.0, -40.0)),
			"Source (x, y, z) lands at game (y, z, x): %s" % spawns["CT"][0]["position"]
		)
		_check(
			is_equal_approx(spawns["CT"][0]["yaw"], 45.0)
				and is_equal_approx(spawns["CT"][1]["yaw"], -90.0),
			"Source yaw is turned half way round (%s, %s)"
				% [spawns["CT"][0]["yaw"], spawns["CT"][1]["yaw"]]
		)
	_check(
		SourceEntities.parse("user://export_fixture/not_there.vents").is_empty(),
		"a missing entity file is no entities, not an error"
	)


## Source 2 Viewer pushes overlays and depth-biased geometry 0.3937 m out
## along their normals. A glTF written by hand, because what matters is the
## bytes: an overlay quad pushed out the way the exporter does it, and an
## ordinary quad that has to come through untouched.
func _test_export_offset_fix() -> void:
	var dir := "user://export_fixture/offsets"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(dir))
	var gltf_path := dir.path_join("world.gltf")
	var bin_path := dir.path_join("world.bin")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(bin_path + ExportOffsetFix.MARKER_SUFFIX))

	# Two quads facing +Z, each with positions and normals of its own, and one
	# index list between them.
	var corners := [Vector3(0, 0, 0), Vector3(1, 0, 0), Vector3(1, 1, 0), Vector3(0, 1, 0)]
	var pushed := Vector3(0.0, 0.0, ExportOffsetFix.EXPORTED_PUSH)
	var bytes := PackedByteArray()
	bytes.resize(4 * 12 * 3 + 6 * 2)
	for i in 4:
		_put_vector(bytes, i * 12, corners[i] + pushed)        # overlay positions
		_put_vector(bytes, 48 + i * 12, corners[i])            # ordinary positions
		_put_vector(bytes, 96 + i * 12, Vector3(0, 0, 1))      # normals, shared
	var indices := [0, 1, 2, 0, 2, 3]
	for i in 6:
		bytes.encode_u16(144 + i * 2, indices[i])
	var bin := FileAccess.open(bin_path, FileAccess.WRITE)
	bin.store_buffer(bytes)
	bin.close()

	var overlay := {"name": "sign", "extras": {"vmat": {
		"ShaderName": "csgo_lightmappedgeneric.vfx", "IntParams": {"F_OVERLAY": 1.0},
	}}}
	var wall := {"name": "wall", "extras": {"vmat": {
		"ShaderName": "csgo_lightmappedgeneric.vfx", "IntParams": {"F_ALPHA_TEST": 1},
	}}}
	var text := FileAccess.open(gltf_path, FileAccess.WRITE)
	text.store_string(JSON.stringify({
		"asset": {"version": "2.0"},
		"buffers": [{"uri": "world.bin", "byteLength": bytes.size()}],
		"bufferViews": [
			{"buffer": 0, "byteOffset": 0, "byteLength": 48},
			{"buffer": 0, "byteOffset": 48, "byteLength": 48},
			{"buffer": 0, "byteOffset": 96, "byteLength": 48},
			{"buffer": 0, "byteOffset": 144, "byteLength": 12},
		],
		"accessors": [
			{"bufferView": 0, "componentType": 5126, "count": 4, "type": "VEC3"},
			{"bufferView": 1, "componentType": 5126, "count": 4, "type": "VEC3"},
			{"bufferView": 2, "componentType": 5126, "count": 4, "type": "VEC3"},
			{"bufferView": 3, "componentType": 5123, "count": 6, "type": "SCALAR"},
		],
		"materials": [overlay, wall],
		"meshes": [{"primitives": [
			{"attributes": {"POSITION": 0, "NORMAL": 2}, "indices": 3, "material": 0},
			{"attributes": {"POSITION": 1, "NORMAL": 2}, "indices": 3, "material": 1},
		]}],
	}))
	text.close()

	_check(ExportOffsetFix.is_pushed(overlay), "an F_OVERLAY material is one the exporter pushes")
	_check(not ExportOffsetFix.is_pushed(wall), "an ordinary material is not")
	_check(
		ExportOffsetFix.is_pushed({"extras": {"vmat": {"ShaderName": "csgo_static_overlay.vfx"}}})
			and ExportOffsetFix.is_pushed({"extras": {"vmat": {"IntParams": {"F_DEPTH_BIAS": 1}}}})
			and not ExportOffsetFix.is_pushed({"name": "no extras at all"}),
		"so are the overlay shader and F_DEPTH_BIAS; a material with no extras is not"
	)

	_check_equal(ExportOffsetFix.fix_file(gltf_path), 4, "the overlay's four vertices are moved")
	var after := FileAccess.get_file_as_bytes(bin_path)
	_check(
		_get_vector(after, 24).is_equal_approx(corners[2] + Vector3(0, 0, ExportOffsetFix.KEPT_PUSH)),
		"back to a quarter of an inch off the wall (%s)" % _get_vector(after, 24)
	)
	_check(_get_vector(after, 48 + 24).is_equal_approx(corners[2]), "the ordinary quad is not touched")
	_check(_get_vector(after, 96).is_equal_approx(Vector3(0, 0, 1)), "nor are the normals")

	_check_equal(ExportOffsetFix.fix_file(gltf_path), 0, "a second run does nothing")
	_check(
		FileAccess.get_file_as_bytes(bin_path) == after,
		"and leaves the file as the first run left it"
	)
	_check(
		JSON.parse_string(FileAccess.get_file_as_string(gltf_path)) is Dictionary,
		"the glTF is still JSON after being touched to force a reimport"
	)


## Godot's glTF import drops the attribute the blend paint arrives in, so it
## is renamed to one it keeps. On the text, which is why this checks the text.
func _test_paint_channel() -> void:
	var dir := "user://export_fixture/paint"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(dir))
	var painted := dir.path_join("painted.gltf")
	var text := '{"asset":{"version":"2.0"},"meshes":[{"primitives":['
	text += '{"attributes":{"POSITION":0,"_TEXCOORD_4":1},"indices":2},'
	text += '{"attributes":{"POSITION":3,"_TEXCOORD_4":4},"indices":5},'
	text += '{"attributes":{"POSITION":6,"COLOR_0":7},"indices":8}]}],"accessors":[{"count":26639}]}'
	_write_text(painted, text)

	_check_equal(ExportPaintChannel.fix_file(painted), 2, "both painted primitives are renamed")
	var after := FileAccess.get_file_as_string(painted)
	_check(
		after.count('"COLOR_0":') == 3 and not after.contains("_TEXCOORD_4"),
		"the paint is COLOR_0 now, next to the vertex colour that was already there"
	)
	_check(
		after.contains('"count":26639'),
		"integers are still integers: the file was edited, not parsed and rewritten"
	)
	_check_equal(ExportPaintChannel.fix_file(painted), 0, "a second run has nothing to do")

	var both := dir.path_join("both.gltf")
	var clash := '{"meshes":[{"primitives":[{"attributes":{"COLOR_0":1,"_TEXCOORD_4":2}}]}]}'
	_write_text(both, clash)
	_check_equal(
		ExportPaintChannel.fix_file(both), -1,
		"a primitive with paint and a vertex colour of its own is refused"
	)
	_check_equal(FileAccess.get_file_as_string(both), clash, "and its file is left as it was")


## The second layer comes from the material's own description plus textures
## fetched by the paths in it. Tiny stand-in textures, laid out as the
## extraction lays them out.
func _test_blend_materials() -> void:
	var dir := "user://export_fixture/layers"
	for texture: String in ["wall_smooth_color", "wall_smooth_normal", "wall_blend"]:
		var path := dir.path_join("materials/test/%s.png" % texture)
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(path.get_base_dir()))
		Image.create(4, 4, false, Image.FORMAT_RGBA8).save_png(path)

	var description := {
		"Name": "materials/test/wall.vmat",
		"IntParams": {"F_LAYERS": 1.0, "F_FANCY_BLENDING": 1.0},
		"FloatParams": {"g_flBlendSoftness": 0.25},
		"VectorParams": {
			"g_vLayer2Tint": [0.5, 0.25, 1.0, 0.0],
			"g_vBlendModulateTexCoordScale": [0.65, 0.65, 0.0, 0.0],
		},
		"TextureParams": {
			"g_tLayer2Color": "materials/test/wall_smooth_color.vtex",
			"g_tLayer2NormalRoughness": "materials/test/wall_smooth_normal.vtex",
			"g_tBlendModulation": "materials/test/wall_blend.vtex",
		},
	}
	var layered := StandardMaterial3D.new()
	layered.resource_name = "wall"
	layered.set_meta("extras", {"vmat": description})
	var plain := StandardMaterial3D.new()
	plain.set_meta("extras", {"vmat": {"IntParams": {"F_ALPHA_TEST": 1.0}}})

	_check(
		BlendMaterials.is_layered(description) and not BlendMaterials.is_layered(BlendMaterials.vmat(plain)),
		"a material is layered if its vmat says F_LAYERS, and not otherwise"
	)
	_check(
		BlendMaterials.build(layered, "user://export_fixture/nowhere") == null,
		"no second layer on disk, no blend material"
	)

	var blend := BlendMaterials.build(layered, dir)
	_check(blend != null, "with its textures extracted, a layered material gets the blend shader")
	if blend != null:
		_check_equal(blend.get_shader_parameter("fancy_blending"), 1, "F_FANCY_BLENDING is carried over")
		_check(
			is_equal_approx(blend.get_shader_parameter("blend_softness"), 0.25)
				and (blend.get_shader_parameter("layer2_tint") as Color).is_equal_approx(Color(0.5, 0.25, 1.0))
				and (blend.get_shader_parameter("mask_uv_scale") as Vector2).is_equal_approx(Vector2(0.65, 0.65)),
			"so are the softness, the tints and the texture scales"
		)
		_check(
			blend.get_shader_parameter("layer2_albedo") is Texture2D
				and blend.get_shader_parameter("blend_modulation") is Texture2D,
			"and the second layer's textures are found by the vmat's own paths"
		)
		_check(
			BlendMaterials.is_layered(BlendMaterials.vmat(blend)),
			"the vmat stays readable on the new material"
		)

	# On a mesh: the layered surface is switched over and the other is not.
	var mesh := ArrayMesh.new()
	for material: Material in [layered, plain]:
		var box := BoxMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, box.get_mesh_arrays())
		mesh.surface_set_material(mesh.get_surface_count() - 1, material)
	var instance := MeshInstance3D.new()
	instance.mesh = mesh
	var meshes: Array[MeshInstance3D] = [instance]
	var result := BlendMaterials.apply(meshes, dir)
	_check_equal(result["blended"], 1, "one surface is blended")
	_check(
		instance.get_surface_override_material(0) is ShaderMaterial
			and instance.get_surface_override_material(1) == null,
		"the layered one, and not its neighbour"
	)

	# The same mesh as it would be without the extraction having fetched layers.
	instance.set_surface_override_material(0, null)
	layered.vertex_color_use_as_albedo = true
	var without := BlendMaterials.apply(meshes, "user://export_fixture/nowhere")
	_check_equal((without["missing"] as PackedStringArray).size(), 1, "a material it could not build is reported")
	_check(
		not layered.vertex_color_use_as_albedo,
		"and is not left tinted by its paint, which is a weight and not a colour"
	)
	instance.free()


## The lighting is a translation of the map's own numbers, so the test is
## that they arrive: from a hand-written entity lump, and, without one, from
## the fallbacks.
func _test_lighting() -> void:
	var entities: Array[Dictionary] = [
		{"classname": "info_player_terrorist", "origin": "[ 0, 0, 0 ]"},
		{
			"classname": "light_environment", "color": "[ 255, 0, 0 ]", "brightness": "2.0",
			"angulardiameter": "0.25", "skycolor": "[ 0, 255, 0 ]", "skyambientbounce": "[ 0, 0, 255 ]",
		},
		{
			"classname": "env_cubemap_fog", "cubemapfogstartdistance": "100.0",
			"cubemapfogenddistance": "5000.0", "cubemapfogmaxopacity": "0.4", "cubemapfogfalloffexponent": "1.5",
		},
		{"classname": "post_processing_volume", "minexposure": "0.5", "maxexposure": "1.5"},
	]
	var holder := Node3D.new()
	root.add_child(holder)
	var used := MapLighting.build(holder, {"basis": Basis.IDENTITY, "color": Color.WHITE}, entities, "")

	var sun := holder.get_node_or_null("Sun") as DirectionalLight3D
	var atmosphere := holder.get_node_or_null("Atmosphere") as WorldEnvironment
	_check(sun != null and atmosphere != null and atmosphere.environment != null, "a sun and an environment are built")
	if sun != null and atmosphere != null:
		var environment := atmosphere.environment
		_check(
			sun.light_color.is_equal_approx(Color(1, 0, 0))
				and is_equal_approx(sun.light_energy, 2.0 * MapLighting.SUN_ENERGY_PER_BRIGHTNESS)
				and is_equal_approx(sun.light_angular_distance, 0.25) and sun.shadow_enabled,
			"the sun's colour, brightness and size come from light_environment"
		)
		_check(
			environment.fog_enabled and is_equal_approx(environment.fog_depth_begin, 100.0)
				and is_equal_approx(environment.fog_depth_end, 5000.0)
				and is_equal_approx(environment.fog_density, 0.4)
				and is_equal_approx(environment.fog_depth_curve, 1.5),
			"the fog's reach and opacity come from env_cubemap_fog"
		)
		_check(is_equal_approx(environment.tonemap_exposure, 1.0), "the exposure is the middle of the post-processing window")
		_check(
			environment.ambient_light_color.is_equal_approx(Color(0, 0, 1))
				and environment.ambient_light_source == Environment.AMBIENT_SOURCE_SKY,
			"the ambient floor is the map's bounce colour, under the sky's light"
		)
		_check(
			environment.sky != null and environment.sky.sky_material is ProceduralSkyMaterial
				and used["sky"].contains("stand-in"),
			"with no panorama on disk the sky is procedural, and the report says so"
		)
		_check(environment.ssao_enabled and environment.glow_enabled, "occlusion and glow are on")
	holder.free()

	var bare := Node3D.new()
	root.add_child(bare)
	var fallback := MapLighting.build(bare, {}, [], "")
	var bare_sun := bare.get_node_or_null("Sun") as DirectionalLight3D
	var bare_env := (bare.get_node_or_null("Atmosphere") as WorldEnvironment).environment
	_check(
		bare_sun != null and bare_sun.light_energy > 0.0 and not bare_env.fog_enabled and not fallback["fog"],
		"with no entities at all there is still a sun, and no fog to hide a grey room in"
	)
	bare.free()


func _write_text(path: String, text: String) -> void:
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string(text)
	file.close()


func _put_vector(bytes: PackedByteArray, at: int, value: Vector3) -> void:
	bytes.encode_float(at, value.x)
	bytes.encode_float(at + 4, value.y)
	bytes.encode_float(at + 8, value.z)


func _get_vector(bytes: PackedByteArray, at: int) -> Vector3:
	return Vector3(bytes.decode_float(at), bytes.decode_float(at + 4), bytes.decode_float(at + 8))


func _spawn_player() -> void:
	var scene: PackedScene = load("res://src/player/player.tscn")
	_player = scene.instantiate() as CharacterBody3D
	_importer.add_child(_player)
	# Above the imported floor, whose top sits at half its height.
	_player.global_position = Vector3(0.0, FLOOR_SIZE.y * 0.5 + 24.0, 0.0)

	# And one over the export-shaped map, above its grenade clip.
	_export_player = scene.instantiate() as CharacterBody3D
	_export_importer.add_child(_export_player)
	_export_player.global_position = EXPORT_OFFSET + Vector3(0.0, 160.0, 0.0)


## The point of the whole exercise: can you stand on an imported map.
func _test_player_stands_on_imported_map() -> void:
	_check(_player != null, "player was spawned on the imported map")
	if _player == null:
		return
	var body := _player as PlayerBody
	_check(body.on_ground, "player is standing on the imported geometry")
	var expected := FLOOR_SIZE.y * 0.5
	_check(
		absf(body.global_position.y - expected) < 2.0,
		"player settled on the floor surface (y = %.2f, expected %.2f)"
			% [body.global_position.y, expected]
	)


## The visible floor's top is at 16 and the hull's at 8, with a grenade clip
## in the way at 64 to 80. Resting at 8 means the hull, only the hull, and not
## all of the hull.
func _test_player_stands_on_the_hull() -> void:
	var body := _export_player as PlayerBody
	_check(body != null and body.on_ground, "player is standing on the export-shaped map")
	if body == null:
		return
	var expected := HULL_FLOOR_SIZE.y * 0.5
	_check(
		absf(body.global_position.y - expected) < 2.0,
		"player fell through the grenade clip and the visible floor onto the hull (y = %.2f, expected %.2f)"
			% [body.global_position.y, expected]
	)


# --- Harness --------------------------------------------------------------

func _check(condition: bool, description: String) -> void:
	_checks += 1
	if condition:
		return
	_failures += 1
	printerr("FAIL: %s" % description)


func _check_equal(actual: Variant, expected: Variant, description: String) -> void:
	_checks += 1
	if actual == expected:
		return
	_failures += 1
	printerr("FAIL: %s (expected %s, got %s)" % [description, expected, actual])


func _report() -> void:
	if _failures == 0:
		print("%d map checks passed." % _checks)
		quit(0)
	else:
		printerr("%d of %d map checks failed." % [_failures, _checks])
		quit(1)
